<a href="https://colab.research.google.com/github/henrykuang/EasyOCR/blob/master/1_Intro_to_pytorch_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [ ]:
import numpy as np

In [ ]:
import torch

In [ ]:
!pip list

List (Python)

In [ ]:
my_list = [[1,2,3,4,5],[7,2,10,0]]
my_list,
type(my_list)

list

NumPy Array

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.3759014 , 0.06780447, 0.37190532, 0.83797123],
       [0.65768897, 0.91016505, 0.51651568, 0.74422102],
       [0.07945851, 0.63420627, 0.72946677, 0.90494161]])

In [ ]:
np1.dtype

dtype('float64')

Tensor

In [ ]:
# [0,1]的均匀分布
tensor_2d = torch.rand(2,4)
tensor_2d

tensor([[0.4399, 0.4206, 0.1345, 0.5326],
        [0.6137, 0.2319, 0.6000, 0.9827]])

In [ ]:
# 正态分布
tensor_normal=torch.normal(mean=2.3,std=0.9,size=(3,5))
print(tensor_normal)

tensor([[2.7588, 2.1449, 1.8984, 3.0575, 4.1802],
        [2.0169, 2.6152, 2.7659, 1.1169, 1.0097],
        [1.6087, 3.2070, 3.3209, 0.8044, 1.6013]])


In [ ]:
# 标准正态分布
tensor_normal2 = torch.randn(size=(3,3))
print(tensor_normal2)

tensor([[-0.9345, -0.7490, -0.3738],
        [-1.4563,  0.7164, -1.4700],
        [ 0.4007,  0.7517, -1.0904]])


In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# create tensor out of numpy array
tensor_x = torch.tensor(np1)
tensor_x

tensor([[0.3759, 0.0678, 0.3719, 0.8380],
        [0.6577, 0.9102, 0.5165, 0.7442],
        [0.0795, 0.6342, 0.7295, 0.9049]], dtype=torch.float64)

In [ ]:
# reshape tensor
tensor_1 = torch.arange(10)
tensor_1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor_1 = tensor_1.reshape(2,5)
tensor_1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# reshape tensor without known the dimension using -1
tensor_2 = torch.arange(10)
tensor_2 = tensor_2.reshape(2,-1)
tensor_2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
tensor_3 = torch.arange(10)
tensor_4 = tensor_3.view(2,5)
tensor_4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
tensor_3[1] = 424
tensor_3

tensor([  0, 424,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
tensor_4

tensor([[  0, 424,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [ ]:
# Slice and dices
tensor_3[7]

tensor(7)

In [ ]:
tensor_8 = tensor_3.reshape(5,2)
tensor_8

tensor([[  0, 424],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

In [ ]:
tensor_9 = tensor_8[:,1]
tensor_9

tensor([424,   3,   5,   7,   9])

In [ ]:
tensor_9 = tensor_8[:,1:]
tensor_9

tensor([[424],
        [  3],
        [  5],
        [  7],
        [  9]])

## **Tensor operations**


In [ ]:
# tensor addition
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# tensor substraction
tensor_b - tensor_a
torch.subtract(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
# tensor multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
torch.multiply(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
# tensor division
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [ ]:
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [ ]:
# tensor reminder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
# tensor exponents to the power of
torch.pow(tensor_b, tensor_a)

tensor([   5,   36,  343, 4096])

In [ ]:
# Another way to write a long hand expression
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# tensor reassignment
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])

In [ ]:
# 张量的数据类型， 整形默认为int64位
p1 = torch.tensor([1,2,3])
print(p1, p1.type())

tensor([1, 2, 3]) torch.LongTensor


In [ ]:
# 张量的数据类型 ， 默认为32位
p2 = torch.tensor([1.2,2.5,3.9])
print(p2, p2.type())

tensor([1.2000, 2.5000, 3.9000]) torch.FloatTensor


In [ ]:
# 张量的数据类型
p3 = torch.tensor([True,False])
print(p3, p3.type())

tensor([ True, False]) torch.BoolTensor


In [ ]:
# 数据类型指定
p4 = torch.tensor([1,2,3], dtype=torch.float32)
print(p4,p4.type())

tensor([1., 2., 3.]) torch.FloatTensor


In [ ]:
# 数据类型转换
p5 = torch.tensor([1,2,3])
p6 = p5.type(torch.float32)
print(p6,p6.type())

tensor([1., 2., 3.]) torch.FloatTensor


In [ ]:
# 张量的升维和降维
t = torch.arange(8)
print(t,t.dim(),t.shape, sep='\n')
t1 = t.unsqueeze(dim=0)
print(t,t1,t1.dim(),t1.shape,sep='\n')

tensor([0, 1, 2, 3, 4, 5, 6, 7])
1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([[0, 1, 2, 3, 4, 5, 6, 7]])
2
torch.Size([1, 8])


In [ ]:
tensor2numpy = t.numpy()
print(tensor2numpy,tensor2numpy.dtype)

[0 1 2 3 4 5 6 7] int64


In [ ]:
tensorfromnumpy = torch.as_tensor(tensor2numpy)
print(tensorfromnumpy)

tensor([0, 1, 2, 3, 4, 5, 6, 7])
